[2022-01-19 18:17:25,009] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Teste.teste manual__2022-01-19T21:17:19.973555+00:00 [queued]>
[2022-01-19 18:17:25,016] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Teste.teste manual__2022-01-19T21:17:19.973555+00:00 [queued]>
[2022-01-19 18:17:25,031] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-19 18:17:25,032] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-19 18:17:25,032] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-19 18:17:25,086] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): teste> on 2022-01-19 21:17:19.973555+00:00
[2022-01-19 18:17:25,093] {standard_task_runner.py:52} INFO - Started process 49282 to run task
[2022-01-19 18:17:25,110] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Teste', 'teste', 'manual__2022-01-19T21:17:19.973555+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/teste.py', '--cfg-path', '/tmp/tmpm90pw6a3', '--error-file', '/tmp/tmpoca9eezw']
[2022-01-19 18:17:25,136] {standard_task_runner.py:77} INFO - Job 25: Subtask teste
[2022-01-19 18:17:25,265] {logging_mixin.py:109} INFO - Running <TaskInstance: Teste.teste manual__2022-01-19T21:17:19.973555+00:00 [running]> on host dataeginner-VirtualBox
[2022-01-19 18:17:25,416] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Teste
AIRFLOW_CTX_TASK_ID=teste
AIRFLOW_CTX_EXECUTION_DATE=2022-01-19T21:17:19.973555+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-19T21:17:19.973555+00:00
[2022-01-19 18:17:25,417] {logging_mixin.py:109} INFO - LAlala
[2022-01-19 18:17:25,417] {python.py:175} INFO - Done. Returned value was: None
[2022-01-19 18:17:25,422] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=Teste, task_id=teste, execution_date=20220119T211719, start_date=20220119T211725, end_date=20220119T211725
[2022-01-19 18:17:25,477] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-19 18:17:25,502] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
