[2022-01-20 21:49:20,719] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Teste.teste scheduled__2022-01-19T22:54:32.956952+00:00 [queued]>
[2022-01-20 21:49:20,760] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Teste.teste scheduled__2022-01-19T22:54:32.956952+00:00 [queued]>
[2022-01-20 21:49:20,760] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-20 21:49:20,760] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-20 21:49:20,761] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-20 21:49:20,804] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): teste> on 2022-01-19 22:54:32.956952+00:00
[2022-01-20 21:49:20,826] {standard_task_runner.py:52} INFO - Started process 120920 to run task
[2022-01-20 21:49:20,861] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Teste', 'teste', 'scheduled__2022-01-19T22:54:32.956952+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/teste.py', '--cfg-path', '/tmp/tmpxg6nk2hq', '--error-file', '/tmp/tmp3b8qa7mp']
[2022-01-20 21:49:20,871] {standard_task_runner.py:77} INFO - Job 26: Subtask teste
[2022-01-20 21:49:21,041] {logging_mixin.py:109} INFO - Running <TaskInstance: Teste.teste scheduled__2022-01-19T22:54:32.956952+00:00 [running]> on host dataeginner-VirtualBox
[2022-01-20 21:49:21,187] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Teste
AIRFLOW_CTX_TASK_ID=teste
AIRFLOW_CTX_EXECUTION_DATE=2022-01-19T22:54:32.956952+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-19T22:54:32.956952+00:00
[2022-01-20 21:49:21,194] {logging_mixin.py:109} INFO - LAlala
[2022-01-20 21:49:21,200] {python.py:175} INFO - Done. Returned value was: None
[2022-01-20 21:49:21,212] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=Teste, task_id=teste, execution_date=20220119T225432, start_date=20220121T004920, end_date=20220121T004921
[2022-01-20 21:49:21,296] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-20 21:49:21,338] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
